# Generated by Django 4.2.3 on 2023-08-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_comment_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_created',)},
        ),
    ]
