# Generated by Django 4.2.3 on 2023-09-01 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0006_category_alter_comment_options_remove_like_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposts',
            field=models.ManyToManyField(blank=True, default=None, related_name='reposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
