version: "3.8"

services:
  web:
    build: .
    container_name: web
    command: python /usr/project/rockstore/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/project/rockstore
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      - POSTGRES_DB=rockstore_project
      - POSTGRES_USER=rockstore_user
      - POSTGRES_PASSWORD=rockstore_project_31
